"""
Word-level cues for every line (guide §3).

Transcribes each padded line with Parakeet, then stretches the word times linearly so the first word
starts and the last word ends exactly where the line sits on the timeline. Writes cues.js:
  window.CUES = { total, lines: {id: [start, end]}, words: {id: [[word, start, end], ...]} }
"""
import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAD = 0.5
NODE_ENV = {**os.environ, "PATH": f"{Path.home()}/.nvm/versions/node/v22.23.1/bin:{os.environ['PATH']}"}


def transcribe(lid: str) -> list[dict]:
    subprocess.run(
        ["npx", "hyperframes", "transcribe", f".work/pad/{lid}.wav", "--json", "--language", "en", "--engine", "parakeet"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        env=NODE_ENV,
        check=True,
    )
    # The CLI writes the word list next to the input file.
    words = json.loads((ROOT / ".work/pad/transcript.json").read_text())
    if not words:
        raise RuntimeError(f"No words for {lid}")
    return words


def main() -> None:
    layout = json.loads((ROOT / "assets/layout.json").read_text())
    words: dict[str, list] = {}
    for lid, (start, end) in layout["lines"].items():
        raw = transcribe(lid)
        if not raw:
            raise RuntimeError(f"{lid}: empty transcript")
        r0 = raw[0]["start"]
        r1 = raw[-1]["end"]
        scale = (end - start) / max(1e-6, r1 - r0)
        words[lid] = [[w["text"], round(start + (w["start"] - r0) * scale, 3), round(start + (w["end"] - r0) * scale, 3)] for w in raw]
        print(f"{lid} {len(raw):2d} words  {' '.join(w['text'] for w in raw)[:80]}")
    cues = {"total": layout["total"], "lines": layout["lines"], "words": words}
    (ROOT / "cues.js").write_text("// Generated by tools/cues.py. Do not edit.\nwindow.CUES = " + json.dumps(cues) + ";\n")
    print(f"wrote cues.js ({sum(len(w) for w in words.values())} words)")


if __name__ == "__main__":
    main()
