/** Real data for the film's visuals: rNVDA hourly closes with US session flags, and Tolu's trades. */
import { writeFileSync } from "node:fs";
import { readSeries } from "../../src/lib/market/store.ts";
import { sessionAt, isUnderlyingClosed } from "../../src/lib/market/sessions.ts";
import { analyze } from "../../src/lib/review/analyze.ts";

const from = Date.UTC(2026, 6, 20), to = Date.UTC(2026, 8, 30);
const bars = readSeries("bitget-spot", "RNVDAUSDT", "1h")!.candles.filter((c) => c.t >= from && c.t < to);
const hours: [number, number, number][] = bars.map((c) => [c.t, Math.round(c.c * 100) / 100, isUnderlyingClosed(sessionAt(c.t)) ? 1 : 0]);
const a = analyze({ kind: "sample" });
const trades = a.facts.map((f, i) => ({ no: i + 1, t: f.trade.entryT, x: f.trade.exitT, ticker: f.trade.ticker, ret: Math.round(f.trade.ret * 10000) / 10000, closed: f.entryClosed, session: f.entrySession }));
writeFileSync("video/assets/data.js", "// Generated by tools/export-data.mts\nwindow.DATA = " + JSON.stringify({ nvda: hours, trades }) + ";\n");
console.log("hours", hours.length, "trades", trades.length);
